title: <p align="center"> Jiayi Wang (Skylar) </p>

logo: "/images/photo.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Jiayi_Wang_resume.pdf">Resume</a> |
  <a href="www.linkedin.com/in/JiayiWang-Skylar">LinkedIn</a> |
  <a href="https://github.com/SkylarWJY">GitHub</a>
  </p>
  
  <p align="justify">
  Data scientist and data analyst with 2-year experience in data analysis, modeling, visualization, and applied statistics
  <br><br>
  Strong technical knowledge of Python, SQL, Spark, R and Tableau as well as adept in leadership roles
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: # Google Analytics tracking ID
